version: '3.9'
services:
  postgres:
    image: postgres:14
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NyNj92
      POSTGRES_DB: nest
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Attach named volume for persistence

  nestjs_app:
    build:
      context: .
    container_name: nestjs_app
    environment:
      DATABASE_URL: postgresql://postgres:NyNj92@postgres:5432/nest
      HOST: 0.0.0.0
      SSP_ROLE_ID: 2
      FARMER_ROLE_ID: 1
      GOOGLE_APPLICATION_CREDENTIALS: /app/keys/service-account.json
    depends_on:
      - postgres
    ports:
      - "3000:3000"  # HTTP
      - "443:443"    # ✅ Added HTTPS port
      - "5555:5555"
    volumes:
      - ./keys/service-account.json:/app/keys/service-account.json  # Mount the JSON key file
      - ./ssl:/app/ssl  # ✅ Mount SSL certs inside the container

# Define the named volume to persist data
volumes:
  postgres_data:
