version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: postgres_container
    restart: always
    env_file:
      - .env  # Load environment variables from .env file
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent database storage

  nestjs_app:
    build:
      context: .
    container_name: nestjs_app
    env_file:
      - .env  # Load environment variables
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "5555:5555"  # Expose Prisma Studio

volumes:
  postgres_data:
