/*
  Warnings:

  - You are about to drop the column `totalLiabilityAmountIncludingPenaltiesAndComprehensiveVehicleIn` on the `Loan` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "Loan" DROP COLUMN "totalLiabilityAmountIncludingPenaltiesAndComprehensiveVehicleIn",
ADD COLUMN     "totalLiabilityAmountIncludingPenaltiesAndComprehensiveVehicleInsurance" TEXT;

-- CreateTable
CREATE TABLE "impact_survey" (
    "id" SERIAL NOT NULL,
    "sheetId" TEXT,
    "creditApplicationId" TEXT,
    "surveyDate" TEXT,
    "directorId" TEXT,
    "createdBy" TEXT,
    "isSchoolAPBETOrPrivate" TEXT,
    "whatKindOfAreaIsTheSchoolIn" TEXT,
    "whatGradeLevelsDoesTheSchoolServe" TEXT,
    "howManyStudentsDoesTheSchoolHave" TEXT,
    "whatPercentageOfChildrenTransitionedLastSchoolYearFromSecondarySchoolToTertiaryOrVocationalSchool" TEXT,
    "thePreviousSchoolYearWhatPercentageOfChildrenPassedTheKCSE" TEXT,
    "howManyClassroomsDoesTheSchoolHave" TEXT,
    "howManyAdministrativeRoomsDoesTheSchoolHave" TEXT,
    "howManyTeachersDoesTheSchoolHave" TEXT,
    "doesTheSchoolHaveADedicatedAssemblyHall" TEXT,
    "howManyPeopleCanTheAssemblyHallSit" TEXT,
    "doesTheSchoolHaveRunningWater" TEXT,
    "describeTheRunningWaterFacilities" TEXT,
    "isTherePurifiedDrinkingWaterAvailableToStudents" TEXT,
    "describeThePurifiedWaterFacilities" TEXT,
    "doesTheSchoolHaveElectricity" TEXT,
    "describeTheElectricalSystem" TEXT,
    "doesTheSchoolHaveFireExtinguishers" TEXT,
    "howManyFireExtinguishers" TEXT,
    "doesTheSchoolProvideMeals" TEXT,
    "doesTheSchoolHaveItsOwnKitchen" TEXT,
    "whatCookingEquipmentDoesTheSchoolHave" TEXT,
    "doesTheSchoolUseCharcoalFirewoodOrGas" TEXT,
    "howManyStudentsEatBreakfastAtTheSchool" TEXT,
    "howManyStudentsEatLunchAtTheSchool" TEXT,
    "describeTheMealsTheSchoolProvides" TEXT,
    "doesTheSchoolOwnVehiclesToTransportStudentsToSchool" TEXT,
    "howManyVehiclesDoesTheSchoolOwn" TEXT,
    "howManyTotalChildrenCanAllOfTheVehiclesFit" TEXT,
    "howManyChildrenAreTransportedEachDay" TEXT,
    "doesTheSchoolHaveItsOwnFields" TEXT,
    "describeTheFacilities" TEXT,
    "howDoesItProvideAccessToFieldsForItsStudents" TEXT,
    "doesTheSchoolHaveADedicatedScienceLab" TEXT,
    "whatDoesTheScienceLabContain" TEXT,
    "doesTheSchoolHaveALibrary" TEXT,
    "howManyBooksDoesTheLibraryContain" TEXT,
    "describeTheLibrary" TEXT,
    "doesTheSchoolHaveAComputerLab" TEXT,
    "howManyWorkingComputersDoesTheComputerLabHave" TEXT,
    "whatIsTheSchoolMadeOf" TEXT,
    "whatAreTheSchoolSFloorsMadeOf" TEXT,
    "isTheSchoolBuildingSingleOrMultistory" TEXT,
    "isTheSchoolBuildingPainted" TEXT,
    "doesTheSchoolHaveAfterSchoolPrograms" TEXT,
    "whatAfterSchoolProgramsDoesTheSchoolHave" TEXT,
    "describeTheSchoolSWashroomFacilities" TEXT,
    "howManyGirlsToiletsDoesTheSchoolHave" TEXT,
    "howManyBoysToiletsDoesTheSchoolHave" TEXT,
    "howManySharedToiletsDoesTheSchoolHave" TEXT,
    "byPercentageOfChildrenHowManyChildrenGetSentHomeAtLeastOncePerTermBecauseOfSchoolFees" TEXT,
    "whenYouWalkedIntoTheSchoolDescribeWhatYouSaw" TEXT,
    "doAnyOfTheTeachersAndAdministrationHaveSmartphones" TEXT,
    "howManyTeachersAndAdminsHaveSmartphones" TEXT,
    "doTheTeachersAndAdministrationHaveComputersPersonallyOrForSchoolWork" TEXT,
    "howManyComputersAreThereForTeachersToUseForWorkOrPersonally" TEXT,
    "howManyFemaleChildrenAttendTheSchool" TEXT,
    "howManyMaleChildrenAttendTheSchool" TEXT,
    "doesTheSchoolHaveTextbooksForStudents" TEXT,
    "howManyStudentsShareEachTextbook" TEXT,
    "isTheSchoolConnectedToASewerLine" TEXT,
    "howManyAdditionalStudentsDoesTheDirectorExpectAnyProjectFinancedOrAssetPurchasedUsingTheLoanProvidedByJackfruitWillAddToTheSchoolIfAny" TEXT,
    "anyOtherNotesOnTheSchool" TEXT,
    "photosAdded" TEXT,
    "isTheSchoolAPartOfASchoolAssociation" TEXT,
    "whichSchoolAssociation" TEXT,
    "doesTheSchoolTakeDailyAttendanceRecords" TEXT,
    "howManyMaleTeachersDoesTheSchoolsHave" TEXT,
    "howManyFemaleTeachersDoesTheSchoolsHave" TEXT,
    "howManyTeachersDidTheSchoolHaveLastYear" TEXT,
    "howManyTeachersDidTheSchoolHaveTwoYearsAgo" TEXT,
    "whatPercentageOfChildrenTransitionedLastSchoolYearFromPrimarySchoolToSecondarySchool" TEXT,
    "whatPercentageOfTeachersFromLastYearCameBackToTeachAgainThisYear" TEXT,
    "howManyGirlsAttendPlaygroupAtTheSchool" TEXT,
    "howManyBoysAttendPlaygroupAtTheSchool" TEXT,
    "howManyGirlsAttendPP1OrPP2AtTheSchool" TEXT,
    "howManyBoysAttendPP1OrPP2AtTheSchool" TEXT,
    "howManyGirlsAttendPrimarySchoolAtTheSchool" TEXT,
    "howManyBoysAttendPrimarySchoolAtTheSchool" TEXT,
    "howManyGirlsAttendSecondarySchoolAtTheSchool" TEXT,
    "howManyBoysAttendSecondarySchoolAtTheSchool" TEXT,
    "howManySpecialNeedsBoysAttendTheSchool" TEXT,
    "howManySpecialNeedsGirlsAttendTheSchool" TEXT,
    "howManyClassroomsDidTheSchoolHaveLastYear" TEXT,
    "howManyClasroomsDidTheSchoolHaveTwoYearsAgo" TEXT,
    "ifTheSchoolIsAPrimarySchoolDoesItHaveAJuniorSecondarySchool" TEXT,
    "doesTheSchoolServeOnlySpecialNeedsStudents" TEXT,
    "howManyMaleEmployeesWhoAreNotTeachersDoesTheSchoolHave" TEXT,
    "howManyFemaleEmployeesWhoAreNotTeachersDoesTheSchoolHave" TEXT,
    "howManyPlayschoolPP1AndPP2TeachersDoesTheSchoolHave" TEXT,
    "howManyPrimaryTeachersDoesTheSchoolHave" TEXT,
    "howManySecondaryTeachersDoesTheSchoolHave" TEXT,
    "approximatelyHowManyTimesAYearDoesTheSchoolTestStudentsInAcademicSubjectsExcludingKPSEAAndKCPE" TEXT,
    "doesTheSchoolMaintainRecordsOfIndividualPupilTestScores" TEXT,
    "howAreRecordsOfPupilTestScoresStored" TEXT,
    "doesTheSchoolMaintainRecordsOfStudentAbsences" TEXT,
    "howAreRecordsOfAbsencesStoredForStudents" TEXT,
    "doesTheSchoolConductMonitoringOfTeachers" TEXT,
    "whenTheSchoolConductsMonitoringOfTeachersIsAFormFilledOut" TEXT,
    "howManyTimesAYearDoesTheSchoolConductMonitoringOfAGivenTeacher" TEXT,
    "doesTheSchoolEvaluateThePerformanceOfTeachers" TEXT,
    "howHowManyTimesPerYearDoesSchoolEvaluateTeachers" TEXT,
    "whatInformationDoesTheSchoolCollectAndUseToEvaluateThePerformanceOfYourTeachers" TEXT,
    "howManyTeachersHaveBeenRemovedForUnsatisfactoryPerformanceInThePast5Years" TEXT,
    "doTeachersReceiveMonetaryRewardsForExceptionalPerformanceYesNo" TEXT,
    "isTheSchoolAMemberOfTheKenyaPrivateSchoolAssociation" TEXT,
    "doYouHaveAChildSafeguardingPolicy" TEXT,
    "whatDoesYourSchoolDoToObserveChildSafeguarding" TEXT,
    "synced" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "impact_survey_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "impact_survey_sheetId_key" ON "impact_survey"("sheetId");
